### ISSUE TITLE
Unexpected Token { (OSX)

### ISSUE THREAD

**Issue by ebtalley** [ibarsi/git-velocity#29]
followed the instructions but am getting a runtime error:

**$** npm install -g git-velocity
/usr/local/bin/git-velocity -> /usr/local/lib/node_modules/git-velocity/dist/index.js
git-velocity@2.2.6 /usr/local/lib/node_modules/git-velocity
├── clear@0.0.1
├── chalk@1.1.3 (escape-string-regexp@1.0.5, ansi-styles@2.2.1, supports-color@2.0.0, has-ansi@2.0.0, strip-ansi@3.0.1)
├── isomorphic-fetch@2.2.1 (whatwg-fetch@2.0.3, node-fetch@1.7.3)
├── blessed@0.1.81
├── figlet@1.2.0
├── moment@2.17.1
├── clui@0.3.1 (cli-color@0.3.2)
├── inquirer@3.0.1 (ansi-escapes@1.4.0, cli-width@2.2.0, through@2.3.8, figures@2.0.0, strip-ansi@3.0.1, mute-stream@0.0.7, run-async@2.3.0, string-width@2.1.1, cli-cursor@2.1.0, external-editor@2.0.5, rx@4.1.0, lodash@4.17.4)
└── blessed-contrib@4.7.5 (ansi-term@0.0.2, memorystream@0.3.1, x256@0.0.2, term-canvas@0.0.5, strip-ansi@3.0.1, marked@0.3.6, sparkline@0.1.2, memory-streams@0.1.2, map-canvas@0.1.5, picture-tube@0.0.4, marked-terminal@1.7.0, drawille-canvas-blessed-contrib@0.1.3, request@2.83.0, lodash@4.17.4)
**$** git-velocity
/usr/local/lib/node_modules/git-velocity/dist/index.js:154
(() => {var _ref = _asyncToGenerator(function* () {try {const { type } = yield getRepositoryType();const commits = (0, _commits.Commits)(type);const isAuthorized = yield commits.isAuthorized();if (!isAuthorized) {console.log();console.log(_chalk2.default.white('Creating auth token in root.'));const { username, password } = yield getRepositoryCreds(type);commits.authorize(username, password);}console.log();console.log(_chalk2.default.white('Provide information regarding the repository you\'d like to analyze.'));const { repository, owner } = yield getRepositoryInfo();const { format } = yield getVelocityFormat();const velocity = (0, _velocity.Velocity)(format);const data = yield (0, _helpers.wrapSpinner)(commits.getCommitsByRepo, 'Pulling commits...')(repository, owner, function (commit) {return !velocity.isDateWithinThisTimeFrame(commit.date) && !velocity.isDateWithinLastTimeFrame(commit.date);});const dashboard = (0, _dashboard2.default)(velocity);yi

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3

**Comment by ibarsi** [comment]
I think this might be due to an old version of Node. What version are you running on your machine?

Currently, Babel is configured to polyfill only those features that are not available on the machine running the build. This doesn't make much sense for a library that's going to be used on many different machines with varying Node versions. I'll change it so that all modern lang features are polyfilled for sure.

**Comment by ebtalley** [comment]
$ node -v
v4.6.0
yeah, its pretty old. I upgraded to current 8.6.0 and its up and running.

**Comment by ibarsi** [comment]
Sweet, I actually just published an updated version that transpiles everything so it should work for older versions of Node now as well :)

Cheers
